# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekfile',
            name='file_type',
            field=models.CharField(default=b'N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='ekfile',
            name='link',
            field=models.CharField(default=b'NULL', max_length=500),
        ),
    ]
