# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20170707_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='ekfile',
            name='link',
        ),
    ]
