# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0003_auto_20170707_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_send_perms', models.BooleanField(default=False)),
                ('add_file_perms', models.BooleanField(default=False)),
                ('usb_get_perms', models.BooleanField(default=False)),
                ('ssid_mod_perms', models.BooleanField(default=False)),
                ('capt_port_perms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
