# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0005_remove_permissions_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_usb_perms', models.BooleanField(default=False)),
                ('add_file_perms', models.BooleanField(default=False)),
                ('usb_read_perms', models.BooleanField(default=False)),
                ('ssid_mod_perms', models.BooleanField(default=False)),
                ('capt_port_perms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
