# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20170708_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
