# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0009_auto_20170711_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(upload_to=b'../../../../../var/www/ekstep'),
        ),
    ]
