# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0011_auto_20170711_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileMetaData',
        ),
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(upload_to=b'.'),
        ),
    ]
