# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0019_auto_20170717_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='folder_file',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='content',
            name='json_file',
        ),
    ]
