# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0021_auto_20170812_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(blank=True, max_length=90, upload_to=b''),
        ),
    ]
