# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0024_auto_20170812_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekfile',
            name='slug',
        ),
    ]
