# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0025_remove_ekfile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekfile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
